config

diff --git a/docker/local/django/start-daphne b/docker/local/django/start-daphne
--- a/docker/local/django/start-daphne
+++ b/docker/local/django/start-daphne
@@ -1,16 +1,39 @@
 #!/bin/bash
-# Fichier: /docker/local/django/start-daphne
 
 set -o errexit
+set -o pipefail
 set -o nounset
 
-python manage.py migrate
+# Attendre que PostgreSQL soit prêt
+python << END
+import sys
+import time
+import psycopg2
+
+suggest_unrecoverable_after = 30
+start = time.time()
+
+while True:
+    try:
+        psycopg2.connect(
+            dbname="${POSTGRES_DB}",
+            user="${POSTGRES_USER}",
+            password="${POSTGRES_PASSWORD}",
+            host="${POSTGRES_HOST}",
+            port="${POSTGRES_PORT}",
+        )
+        break
+    except psycopg2.OperationalError as error:
+        sys.stderr.write("Waiting for PostgreSQL to become available...\n")
+        if time.time() - start > suggest_unrecoverable_after:
+            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
+    time.sleep(1)
+END
+
+>&2 echo 'PostgreSQL is available'
+
+# Collecter les fichiers statiques
 python manage.py collectstatic --noinput
 
-
-PROJECT_NAME="${DJANGO_PROJECT_NAME:-notification}"
-echo "Starting Daphne for project: ${PROJECT_NAME}"
-
-exec daphne -b 0.0.0.0 -p 9082 notification.asgi:application
-
-# exec daphne -b 0.0.0.0 -p 9082 ${PROJECT_NAME}.asgi:application
+# Démarrer Daphne
+exec daphne -b 0.0.0.0 -p 9082 config.asgi:application
